### ISSUE TITLE
Vector.to_list returns a reversed list

### ISSUE THREAD

**Issue by copy** [IndiscriminateCoding/clarity#1]
For example:

```ocaml
#require "clarity";;
open Clarity.Vector;;
get (of_list [1;2;3]) 0;;
(* - : int = 1 *)
to_list (of_list [1;2;3]);;
(* - : int list = [3; 2; 1] *)
```

**Comment by IndiscriminateCoding** [comment]
Yeah, that was fixed some time ago. Using library from master branch (and not opam) should fix the problem.

**Comment by IndiscriminateCoding** [comment]
That was fixed some time ago, but fix still not in opam. I'll try to deliver new version to opam soon.

**Comment by IndiscriminateCoding** [comment]
Closing this issue as version 0.3.0 was merged into opam repository. Feel free to report/reopen if you will have any issues.
