### ISSUE TITLE
Implement Vector.push

### ISSUE THREAD

**Issue by copy** [IndiscriminateCoding/clarity#4]
A `Vector.push : 'a t -> 'a -> 'a t` would be nice. With the current public interface, it can only be implemented using `Vector.append vec (Vector.pure x)`.

**Comment by IndiscriminateCoding** [comment]
Note that appending singleton vector to RRB-tree would be "effectively constant" operation.
It's possible to slightly optimize constant part, but "pushing" element to vector inside a loop wouldn't be very performant anyway.
Best approach would be to expose some Vector.Builder module allowing to efficiently construct Vectors by appending elements by-one (and internally something similar already used for operations like init, bind or of_list).
But of course, something like "cons" and "snoc" functions would be nice to have anyway.

**Comment by IndiscriminateCoding** [comment]
[Opam repository PR for this change](https://github.com/ocaml/opam-repository/pull/12587).
Note also that 0.4.0 adds Vector.Builder, which can be used to construct vectors much more efficiently than using cons/snoc.
